version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run: pip install --user -r requirements.txt
      - run: /home/circleci/.local/bin/tox
  deploy:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run: pip install --user -r requirements.txt
      - run: /home/circleci/.local/bin/tox python setup.py bdist_egg
      - store_artifacts:
          path: ./build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
